// <auto-generated />
using F1API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace F1API.Migrations
{
    [DbContext(typeof(F1Context))]
    [Migration("20220331210934_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("F1API.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Team")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            Age = 37,
                            Name = "Lewis Hamilton",
                            Team = "Mercedes"
                        },
                        new
                        {
                            DriverId = 2,
                            Age = 24,
                            Name = "Max Verstappen",
                            Team = "Red Bull"
                        },
                        new
                        {
                            DriverId = 3,
                            Age = 32,
                            Name = "Daniel Ricciardo",
                            Team = "McLaren"
                        },
                        new
                        {
                            DriverId = 4,
                            Age = 27,
                            Name = "Carlos Sainz",
                            Team = "Ferrari"
                        },
                        new
                        {
                            DriverId = 5,
                            Age = 34,
                            Name = "Aston Martin",
                            Team = "Astin Martin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
